# Generated by Django 4.2.28 on 2026-02-12 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fieldtrip_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldtrip',
            name='school',
        ),
    ]
